klass:
  students:
    - id: 1
      name: zhangsan
    - id: 1
      name: lisi

student:
  id: 1
  name: wangwu

school:
  klass:
    students:
      - id: 1
        name: zhangsan
      - id: 1
        name: lisi
  student:
    id: 1
    name: wangwu
